### ISSUE TITLE
Configurable name overwrite for get-object-url

### ISSUE THREAD

**Issue by dhryniewicz** [gethop-dev/object-storage.s3#1]
The object downloaded using the generated url by default is going to be named as the last section (to the right of the last `/` symbol) of the object key. If, for whatever reason, you use UUIDs as object keys for your files then not only the name is meaningless but it doesn’t have the extension even! So you won’t be able to open, say, a PNG image you uploaded to S3 unless you change the name properly.

Our colleague @iarenaza found a way to work around it:
```clojure
(require '[amazonica.aws.s3 :as s3])
(import '[com.amazonaws.services.s3.model ResponseHeaderOverrides])

(let [headers (->
               (ResponseHeaderOverrides.)
               (.withContentDisposition "attachment; filename=my-fancy-filename.docx"))
      presigned-url (->
                     (s3/generate-presigned-url {:bucket-name "hydrogen-test"
                                                 :key "images/DSCN2922.JPG"
                                                 :response-headers headers})
                     (.toString))]
  (pprint presigned-url))
```

It would be nice to have our protocol support a filename overwrite.

**Comment by iarenaza** [comment]
Fixed in release 0.5.0
